print("Profile")
print("What is your name?")
name = input(">")
print("What is your age?")
age = input(">")
print("Where do you live?")
city = input(">")
print("My name is "+ name)
print("I am "+ age + "years old")
print("I live in "+ city)
